////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2008 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 1.0Release
// Tag = $Name: AKW1_000 $
////////////////////////////////////////////////////////////////////////////////


package com.lancea12.MyTrainingPage.server;

import com.garmin.fit.*;

import java.util.Collection;
import java.util.Iterator;

public class MesgToTrainingDataAdapter implements MesgListener, MesgDefinitionListener {

	private boolean inLap = false;
	
	public MesgToTrainingDataAdapter() {

	}

	public void close() {

	}

	public void onMesgDefinition(MesgDefinition mesgDef) {
		Collection<FieldDefinition> fields = mesgDef.getFields();
		Iterator<FieldDefinition> fieldsIterator;
		int fieldNum;
		Mesg mesg = Factory.createMesg(mesgDef.getNum());



		if (mesg == null)
		{

		}
		else
		{
			//System.out.println("defining " + mesg.getName());
		}

		fieldNum = 0;
		fieldsIterator = fields.iterator();

		while (fieldsIterator.hasNext()) {
			FieldDefinition fieldDef = fieldsIterator.next();
			Field field = Factory.createField(mesgDef.getNum(), fieldDef.getNum());
			fieldNum++;

			if (field == null)
			{

			}
			else
			{

			}


		}


	}

	public void onMesg(Mesg mesg) {
		Collection<Field> fields = mesg.getFields();
		Iterator<Field> fieldsIterator;
		int fieldNum;

		fieldsIterator = fields.iterator();

		System.out.println(mesg.getName());
		
		//if (mesg.getName().equals("event") || mesg.getName().equals("record")){
			while (fieldsIterator.hasNext()) {
				Field field = fieldsIterator.next();

				System.out.println("\t" + field.getName() + " = " + field.getValue());


			}
		//}



		//System.out.println(mesg.getField(0).getName() + " = " + mesg.getFieldStringValue(0));






	}
}
